apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ibuki-bluearchive-api

resources:
  - rss-state-pvc.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pdb.yaml
  - export-students-cronjob.yaml
  - secrets/sealedsecret.yaml

images:
  - name: docker.io/kemar1/bluearchive-api
    newTag: v3.0.3
  - name: docker.io/kemar1/bluearchive-api-go
    newTag: v3.0.3
  - name: docker.io/kemar1/bluearchive-og-renderer
    newTag: v3.0.3
  - name: docker.io/kemar1/bluearchive-export-students
    newTag: v3.0.3

configMapGenerator:
  - name: students-config
    files:
      - students.json=data/students.json

generatorOptions:
  disableNameSuffixHash: false
