apiVersion: v1
kind: Service
metadata:
  name: bluearchive-postgres
  labels:
    app: bluearchive-postgres
spec:
  clusterIP: None
  selector:
    app: bluearchive-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
