apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bluearchive-rss-state
  labels:
    app: bluearchive-go-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
