apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bluearchive-students-data
  labels:
    app: bluearchive-go-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
