apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluearchive-api
  labels:
    app: bluearchive-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bluearchive-api
  template:
    metadata:
      labels:
        app: bluearchive-api
    spec:
      initContainers:
        - name: seed-students-data
          image: docker.io/kemar1/bluearchive-api:0.2.1
          command:
            - /bin/sh
            - -c
          args:
            - |
              if [ ! -f /students-data/students.json ]; then
                cp /app/data/students.json /students-data/students.json;
              fi
          volumeMounts:
            - name: students-data
              mountPath: /students-data
      containers:
        - name: bluearchive-api
          image: docker.io/kemar1/bluearchive-api:0.2.1
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
              name: http
          readinessProbe:
            httpGet:
              path: /api
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: students-data
              mountPath: /app/data
      volumes:
        - name: students-data
          persistentVolumeClaim:
            claimName: bluearchive-api-data