apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluearchive-api
  labels:
    app: bluearchive-api
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bluearchive-api
  template:
    metadata:
      labels:
        app: bluearchive-api
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      initContainers:
        - name: seed-students-data
          image: docker.io/kemar1/bluearchive-api:1.1.0
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
          args:
            - |
              set -e
              # Git（ConfigMap）の内容で毎回上書きして Git 優先を担保
              cp -f /seed/students.json /students-data/students.json
              chown -R 1000:1000 /students-data
          volumeMounts:
            - name: students-data
              mountPath: /students-data
            - name: students-seed
              mountPath: /seed
              readOnly: true
      containers:
        - name: bluearchive-api
          image: docker.io/kemar1/bluearchive-api:1.1.0
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
          env:
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
              name: http
          readinessProbe:
            httpGet:
              path: /api
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: students-data
              mountPath: /app/data
      volumes:
        - name: students-data
          persistentVolumeClaim:
            claimName: bluearchive-api-data
        - name: students-seed
          configMap:
            name: students-config
            items:
              - key: students.json
                path: students.json
