apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bluearchive-api-test
  labels:
    name: bluearchive-api-test
spec:
  ingressClassName: traefik
  rules:
    - host: bluearchive-api-test.skyia.jp
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: bluearchive-api-test
                port:
                  number: 80