apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bluearchive-api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: ibuki-api-test.uniproject.jp
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bluearchive-api
                port:
                  number: 80
