apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bluearchive-api-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-rwx
