apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bluearchive-api-data
  namespace: ibuki-bluearchive-api
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1Gi
