apiVersion: v1
kind: Service
metadata:
  name: bluearchive-frontend
spec:
  selector:
    app: bluearchive-frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: bluearchive-go-api
spec:
  selector:
    app: bluearchive-go-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: bluearchive-og-renderer
spec:
  selector:
    app: bluearchive-og-renderer
  ports:
    - name: http
      port: 80
      targetPort: 8787
  type: ClusterIP
